print("Zahlen in Python")
print("")
print("Rechnung 1")
print("Aufgabe:", "7 + 4")
print("Ergebnis:",7 +4)
print("")
print("Rechnung 2")
print("Aufgabe:", "7 - 4")
print("Ergebnis:",7 -4)
print("")
print("Rechnung 3")
print("Aufgabe:", "8 * 4")
print("Ergebnis:", 8 * 4)
print("")
print("Rechnung 4")
print("Aufgabe:", "8 / 4")
print("Ergebnis:", 8 / 4)
print("")
print("Rechnung 5")
print("Aufgabe:", "3 + 2 * 2 - 1")
print("Ergebnis:", 3 + 2 * 2 - 1)
print("")
print("Rechnung 6")
print("Aufgabe:", "(3 + 2) * (2 - 1)")
print("Ergebnis:", (3 + 2) * (2 - 1))
print("")
print("Rechnung 7")
print("Aufgabe:", "2.1 + 1.5")
print("Ergebnis:", 2.1 + 1.5)
print("")
print("Rechnung 8")
print("Aufgabe:", "2.4 * 2")
print("Ergebnis:", 2.4 * 2)