print("Daten für den Raum angeben: ")
print("")
number = input("Bitte Nummer des Raumes angeben: ")
size = input("Größe des Raumes in m²: ")
windows = input("Anzahl der Fenster: ")
floor = input("Stockwerk: ")
color = input("Wandfarbe: ")
flooring = input("Bodenbelag: ")
furnished = input("Möbliert (Ja/Nein): ")
sockets = input("Anzahl der Steckdosen: ")
daylight = input("Tageslicht (Ja/Nein): ")
wifi = input("WLAN verfügbarkeit (Ja/Nein): ")
print("")

print("Zimmerdaten:")
print("")
output01 = "Nummer des Raumes: "  + str(number)
output02 = "Größe des Raumes in m²: " + str(size)
output03 = "Anzahl der Fenster: " + str(windows)
output04 = "Stockwerk: " + str(floor)
output05 = "Wandfarbe: " + (color)
output06 = "Bodenbelag: " + (floor)
output07 = "Möbliert: " + (furnished)
output08 = "Anzahl der Steckdosen: " + str(sockets)
output09 = "Tageslicht: " + (daylight)
output10 = "WLAN verfügbarkeit: " + (wifi)

print(output01)
print(output02)
print(output03)
print(output04)
print(output05)
print(output06)
print(output07)
print(output08)
print(output09)
print(output10)